### ISSUE TITLE
Config validation requires undocumented options

### ISSUE THREAD

**Issue by clerie** [wobcom/fernglas#10]
When I try to set up the BGP collector for Fernglas according to the sample config from [the documentation](https://github.com/wobcom/fernglas/blob/71766d09dc6a43c2219d57c6372a1b5934b61a99/manual/src/data-sources/README.md?plain=1#L26-L31), I get errors while validating configuration.

```
Error: collectors: missing field `route_state` at line 1 column 43
```

```
Error: collectors: missing field `add_path` at line 1 column 43
```

I used to following config:

```json
{
  "api": {
    "bind": "[::1]:3000"
  },
  "collectors": [
    {
      "bind": "[::]:1179",
      "collector_type": "Bgp",
      "default_peer_config": {
        "asn": 4242422953,
        "router_id": "192.168.10.28"
      }
    }
  ]
}
```

Based on information I gathered from the source code I changed my configuration to this:

```json
{
  "api": {
    "bind": "[::1]:3000"
  },
  "collectors": [
    {
      "bind": "[::]:1179",
      "collector_type": "Bgp",
      "default_peer_config": {
        "add_path": true,
        "asn": 4242422953,
        "route_state": "Accepted",
        "router_id": "192.168.10.28"
      }
    }
  ]
}
```

It is not clear to me what these options do and whether my values make sense.

Please [add documentation](https://github.com/wobcom/fernglas/blob/71766d09dc6a43c2219d57c6372a1b5934b61a99/manual/src/data-sources/README.md?plain=1#L50-L54) to clarify and revise config validation if this is a bug.

**Comment by yu-re-ka** [comment]
This was solved out of band, and was caused by a mismatch between the documentation used and the version deployed (latest development commit vs. 0.1.0 release)
