### ISSUE TITLE
fernglas daemon dies when using flowspec

### ISSUE THREAD

**Issue by Commander1024** [wobcom/fernglas#13]
Ohai,

we just noticed fighting some dos traffic using flowspec the fernglas deamon repeatedly died.

```
Nov 30 22:21:01 looking-glass fernglas[1426]: thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zettabgp-0.3.4/src/afi/flowspec.rs:450:52:
Nov 30 22:21:01 looking-glass fernglas[1426]: slice index starts at 2 but ends at 1
```

This is running the latest self-compiled build from the main branch.
Please feel free to request more information, if needed.

Greetings,
Commander1024

**Comment by yu-re-ka** [comment]
Hi, if we could get a dump of the BMP stream that is causing this issue, that would be very useful. You can - in place of the fernglas server - start a tcp server that writes everything it receives to disk `mbuffer  -I 11019 | zstd > bmp-dump.zst`.
Leave this running for a few minutes and mail the file to yureka@wobcom.de (or share it here in the issue if it can be public).

**Comment by Commander1024** [comment]
Ohai,

jumping in real quick with some non-information.
Probably there's not going to happen much here till the end of the year - there are currently just no ressources for debugging this with x-mas on the horizon. But we did not observe any crashes since then - but we did not have to flowspec around DDoS'es either.

So I wish you a Merry Christmas and a happy new year :-)

Commander1024

**Comment by yu-re-ka** [comment]
Is your instance public? I'm curious :)
hope you have good holidays

**Comment by Commander1024** [comment]
It is :-)

[lg.tkrz.net](https://lg.tkrz.net)

**Comment by yu-re-ka** [comment]
Hi, is there any news on dumping the BMP stream for debugging purposes? :)

**Comment by Commander1024** [comment]
We could not reproduce, meaning not a single crash anymore - also not when flowspeccing traffic. So I'm going to close this. Thanks for your patience.
